### PR TITLE
Allow Transaction::setHints before the transaction has started

### PR DESCRIPTION
**Pull request by aleasto**

### CODE REVIEW

**Comment by aleixpol** [comment]
TBH, I find it quite odd that they override... it makes the API quite unpredictable. @dantti do you know why it was implemented this way?

**Comment by dantti** [comment]
Currently, we have a Global::hints that can be set so all transactions use that instead those hints were always sent.
If one called Transaction::setHints() this would set new hints on that transaction, what PK does then I'm not sure.

Now if you want to change the transaction hints but want to remove some key set at Global::hints how else can you do it? I find it better to manually append then.

But IMO this PR doesn't make it clear that Global::hints exist and would be used (text was removed), I'm not sure about the use-case here but I see the value of being able to control hints

**Comment by aleasto** [comment]
> Now if you want to change the transaction hints but want to remove some key set at Global::hints how else can you do it? I find it better to manually append then.

Yea i agree, it has to be implemented to overwrite.

**Comment by aleasto** [comment]
@dantti I've tried to improve the documentation to clarify the relation with `Daemon::setHints`. Is this ok?

**Pull request merged**
