### PR TITLE
Return early when `role == Transaction::RoleUnknown`

### PR DESCRIPTION
**Pull request by CatEricka**
An alternative to #45.

### CODE REVIEW

**Comment by CatEricka** [comment]
> Does this fix the issue you are seeing as well? If so, this is a much nicer fix!

I believe so.

After two months of suffering, I still can't understand why this is happening. However, I think it is a correct decision to return directly when the role is unknown.

I have also left enough clues for others who want to continue to dig this issue, but for now, just put an end to this desktop crash nightmare. (Meanwhile `libkscreen` is still crashing my desktop...)

**Comment by CatEricka** [comment]
I've installed this patch on my physical machine and it's working fine so far. #42 fixed, and #41 should also be fixed.

**Review by ximion — CHANGES_REQUESTED** [review]
> After two months of suffering, I still can't understand why this is happening.

Well, that's fairly easy: When there's an unknown role, `reply` is not initialized, so trying to use it later will crash.
The question is: Why did you have a transaction with an unknown role in the first place?

I would be happier with this patch if instead of adding a case for `RoleUnknown` you'd change it so we return if we can't handle the transaction role:
```cpp
    default:
        return;
``` 

That we, the chance of this issue reappearing is fairly low.
I assume your unknown role comes from an initialization, however, if that were the case I should have been able to reproduce this 100% of the time, so it's still a bit odd to me.

**Comment by CatEricka** [comment]
According to my observation, `apper` creates a new transaction with the same tid (from signal `DBusInterface::watchTransaction` [here](https://github.com/KDE/apper/blob/7362350ddae29508d5af70ae41277a78c88d6c94/apperd/ApperdThread.cpp#L135) ) after [creating an update transaction](https://github.com/KDE/apper/blob/7362350ddae29508d5af70ae41277a78c88d6c94/apperd/Updater.cpp#L95). And the value of the second transaction object is not initialized by setup.

https://github.com/PackageKit/PackageKit-Qt/pull/45#issuecomment-1381258412

**Comment by CatEricka** [comment]
In other words, `apper` gets a transaction id created by other code (for example, apt update hook), and then use the same tid to [create a new Transaction](https://github.com/PackageKit/PackageKit-Qt/blob/73d84e355457361091244676d0c1a0891b30c189/src/transaction.cpp#L63) for watch signals. Is this the correct way to use it?

**Comment by CatEricka** [comment]
> I would be happier with this patch if instead of adding a case for RoleUnknown you'd change it so we return if we can't handle the transaction role

I also agree with this, but I noticed that `Role::RoleCancel` was not handled before, so I chose a more conservative modification.

**Comment by CatEricka** [comment]
>I assume your unknown role comes from an initialization, however, if that were the case I should have been able to reproduce this 100% of the time, so it's still a bit odd to me.

A fresh install of debian testing (bookworm) should reproduce this, at least according to reports from debian and kde's bug tracker :)

**Review by CatEricka — COMMENTED** [review]
looks good for me

**Review by ximion — APPROVED** [review]
Looks good to me now, this change makes sense!
Thank you for your patch and the debugging work!

**Pull request merged**
